import type { AppPageId } from "../stores/appStore";
import type { ConsoleRouteDefinition, ConsoleRouteGroup } from "../types/console";

export const CONSOLE_ROUTES: ConsoleRouteDefinition[] = [
  {
    id: "dashboard",
    path: "/",
    navLabel: "概览",
    eyebrow: "Overview",
    title: "后台概览",
    description: "查看系统健康、账号状态和接管概览",
    visibleInNav: true,
    group: "workspace",
    order: 10,
    icon: "dashboard",
    dataBadges: [{ label: "API", tone: "api", detail: "健康检查 / 指标 / 运行时 / 队列" }],
    progress: { label: "已接通", tone: "done", detail: "核心概览已接真实数据" },
  },
  {
    id: "conversations",
    path: "/conversations",
    navLabel: "会话工作台",
    eyebrow: "Workspace",
    title: "会话工作台",
    description: "处理 AI 托管、人工接管和多账号会话",
    visibleInNav: true,
    group: "workspace",
    order: 20,
    icon: "workspace",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "会话 / 消息 / 运行时" }],
    progress: { label: "进行中", tone: "in_progress", detail: "工作台持续完善" },
  },
  {
    id: "meta",
    path: "/meta/accounts",
    navLabel: "Meta 账户",
    eyebrow: "Accounts",
    title: "Meta 账户管理",
    description: "管理 WABA、号码、Webhook 和 Embedded Signup",
    visibleInNav: true,
    group: "people",
    order: 10,
    icon: "accounts",
    dataBadges: [{ label: "API", tone: "api", detail: "Meta 账户 / 号码 / Webhook" }],
    progress: { label: "进行中", tone: "in_progress", detail: "多账号接入主线" },
  },
  {
    id: "templates",
    path: "/templates",
    navLabel: "模板消息",
    eyebrow: "Templates",
    title: "模板消息中心",
    description: "管理模板草稿、审核状态、发送日志和统计",
    visibleInNav: true,
    group: "content",
    order: 10,
    icon: "templates",
    dataBadges: [{ label: "API", tone: "api", detail: "模板 / 发送日志 / 统计" }],
    progress: { label: "进行中", tone: "in_progress", detail: "模板闭环持续补全" },
  },
  {
    id: "whatsapp_stats",
    path: "/analytics/whatsapp",
    navLabel: "WhatsApp 统计",
    eyebrow: "Analytics",
    title: "WhatsApp 统计",
    description: "查看消息量、计费分解和趋势分析",
    visibleInNav: false,
    group: "analytics",
    order: 10,
    icon: "analytics",
    dataBadges: [{ label: "API", tone: "api", detail: "统计概览 / 日明细 / 详情" }],
    progress: { label: "已接通", tone: "done", detail: "统计面板已接真实数据" },
  },
  {
    id: "media",
    path: "/assets/media",
    navLabel: "媒体库",
    eyebrow: "Assets",
    title: "媒体库",
    description: "查看模板媒体资产与引用情况",
    visibleInNav: true,
    group: "content",
    order: 20,
    icon: "media",
    dataBadges: [{ label: "API", tone: "api", detail: "媒体资产 / 详情 / 上传" }],
    progress: { label: "进行中", tone: "in_progress", detail: "媒体资产管理已可用" },
  },
  {
    id: "tags",
    path: "/assets/tags",
    navLabel: "标签",
    eyebrow: "Assets",
    title: "标签管理",
    description: "维护用户和会话标签",
    visibleInNav: true,
    group: "content",
    order: 30,
    icon: "tags",
    dataBadges: [{ label: "API", tone: "api", detail: "平台标签 / 新建标签" }],
    progress: { label: "已接通", tone: "done", detail: "标签管理已接真实接口" },
  },
  {
    id: "audience_rules",
    path: "/assets/audience-rules",
    navLabel: "受众规则",
    eyebrow: "Assets",
    title: "受众规则",
    description: "管理细分规则与触达条件（已合并入标签 Tab）",
    visibleInNav: false,
    group: "content",
    order: 35,
    icon: "audience_rules",
    dataBadges: [{ label: "API", tone: "api", detail: "受众规则 / 新建规则" }],
    progress: { label: "已接通", tone: "done", detail: "受众规则管理已接真实接口" },
  },
  {
    id: "ecommerce",
    path: "/ecommerce",
    navLabel: "商城数据",
    eyebrow: "Commerce",
    title: "商城数据",
    description: "查看最小订单与物流接口",
    visibleInNav: true,
    group: "content",
    order: 40,
    icon: "ecommerce",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "真实查询优先，缺口走模拟" }],
    progress: { label: "进行中", tone: "in_progress", detail: "保持最小边界，不继续深挖" },
  },
  {
    id: "task_rules",
    path: "/marketing/task-rules",
    navLabel: "任务规则",
    eyebrow: "Marketing",
    title: "任务规则管理",
    description: "管理推送规则、签到配置和任务统计",
    visibleInNav: true,
    group: "content",
    order: 50,
    icon: "audience_rules",
    dataBadges: [{ label: "模拟", tone: "mock", detail: "推送规则 / 签到 / 邀请 / 统计" }],
    progress: { label: "进行中", tone: "in_progress", detail: "规则管理已可浏览" },
  },
  {
    id: "invite_management",
    path: "/marketing/invites",
    navLabel: "邀请管理",
    eyebrow: "Marketing",
    title: "邀请管理",
    description: "独立管理邀请配置、奖励参数和邀请统计",
    visibleInNav: true,
    group: "content",
    order: 55,
    icon: "audience_rules",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "邀请配置 / 邀请统计 / 真实接口优先" }],
    progress: { label: "进行中", tone: "in_progress", detail: "邀请闭环已收口为独立入口" },
  },
  {
    id: "invite_relations",
    path: "/marketing/invite-relations",
    navLabel: "邀请关系",
    eyebrow: "Marketing",
    title: "邀请关系",
    description: "查看邀请人、被邀请人、邀请类型和风险线索",
    visibleInNav: true,
    group: "content",
    order: 56,
    icon: "audience_rules",
    dataBadges: [{ label: "API", tone: "api", detail: "邀请关系 / 奖励状态 / 风险线索" }],
    progress: { label: "进行中", tone: "in_progress", detail: "邀请关系已迁出为独立正式页面" },
  },
  {
    id: "invite_rewards",
    path: "/marketing/invite-rewards",
    navLabel: "邀请奖励",
    eyebrow: "Marketing",
    title: "邀请奖励流水",
    description: "查看邀请奖励金额、入账状态和资金口径",
    visibleInNav: true,
    group: "content",
    order: 57,
    icon: "audience_rules",
    dataBadges: [{ label: "API", tone: "api", detail: "奖励金额 / 入账状态 / 资金口径" }],
    progress: { label: "进行中", tone: "in_progress", detail: "邀请奖励流水已迁出为独立正式页面" },
  },
  {
    id: "tasks",
    path: "/collaboration/tasks",
    navLabel: "任务",
    eyebrow: "Collaboration",
    title: "任务中心",
    description: "查看任务模板、实例和状态",
    visibleInNav: true,
    group: "people",
    order: 20,
    icon: "tasks",
    dataBadges: [{ label: "API", tone: "api", detail: "任务模板 / 任务实例 / 任务认领" }],
    progress: { label: "进行中", tone: "in_progress", detail: "任务中心已接真实任务接口" },
  },
  {
    id: "reviews",
    path: "/collaboration/reviews",
    navLabel: "审核队列",
    eyebrow: "Collaboration",
    title: "审核队列",
    description: "查看待审核和驳回事项",
    visibleInNav: true,
    group: "workspace",
    order: 60,
    icon: "reviews",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "审核队列真实接口优先，缺口回退本地队列" }],
    progress: { label: "进行中", tone: "in_progress", detail: "审核队列已可联调" },
  },
  {
    id: "tickets",
    path: "/collaboration/tickets",
    navLabel: "工单",
    eyebrow: "Collaboration",
    title: "工单中心",
    description: "查看转人工、异常和跟进工单",
    visibleInNav: true,
    group: "workspace",
    order: 40,
    icon: "tickets",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "工单真实接口优先，缺口回退本地记录" }],
    progress: { label: "进行中", tone: "in_progress", detail: "工单处理页已可联调" },
  },
  {
    id: "members",
    path: "/collaboration/members",
    navLabel: "客服团队",
    eyebrow: "Collaboration",
    title: "客服团队",
    description: "查看客服成员、状态和负载",
    visibleInNav: true,
    group: "people",
    order: 10,
    icon: "members",
    dataBadges: [{ label: "API", tone: "api", detail: "运行时坐席 / 负载 / 状态" }],
    progress: { label: "进行中", tone: "in_progress", detail: "成员主线已接入" },
  },
  {
    id: "assignments",
    path: "/collaboration/assignments",
    navLabel: "我的队列",
    eyebrow: "Collaboration",
    title: "会话分配",
    description: "查看分配队列、接管建议和处理状态",
    visibleInNav: true,
    group: "workspace",
    order: 30,
    icon: "assignments",
    dataBadges: [{ label: "API", tone: "api", detail: "会话 / 分配 / 接管" }],
    progress: { label: "进行中", tone: "in_progress", detail: "分配页已联调" },
  },
  {
    id: "automation",
    path: "/collaboration/automation",
    navLabel: "自动分配规则",
    eyebrow: "Collaboration",
    title: "自动化规则",
    description: "管理自动化触发规则和执行策略",
    visibleInNav: false,
    group: "people",
    order: 50,
    icon: "automation",
    dataBadges: [{ label: "模拟", tone: "mock", detail: "规则编排以前端模拟为主" }],
    progress: { label: "进行中", tone: "in_progress", detail: "规则中心已可浏览" },
  },
  {
    id: "customers",
    path: "/collaboration/customers",
    navLabel: "客户",
    eyebrow: "Collaboration",
    title: "客户视图",
    description: "查看客户档案、标签和关联会话",
    visibleInNav: true,
    group: "workspace",
    order: 50,
    icon: "customers",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "平台用户 / 会话 / 工单" }],
    progress: { label: "进行中", tone: "in_progress", detail: "客户 360 视图已可浏览" },
  },
  {
    id: "monitoring",
    path: "/monitoring",
    navLabel: "监控健康",
    eyebrow: "Monitoring",
    title: "监控与健康",
    description: "查看健康检查、队列运行态和基础指标",
    visibleInNav: true,
    group: "devops",
    order: 10,
    icon: "monitoring",
    dataBadges: [{ label: "API", tone: "api", detail: "健康检查 / 指标 / 队列" }],
    progress: { label: "已接通", tone: "done", detail: "运行态与健康检查可用" },
  },
  {
    id: "api_webhooks",
    path: "/system/api-webhooks",
    navLabel: "API / Webhook",
    eyebrow: "System",
    title: "API / Webhook",
    description: "查看回调订阅、签名失败、回放积压和策略（已合并入集成管理 Tab）",
    visibleInNav: false,
    group: "settings",
    order: 35,
    icon: "webhooks",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "Webhook 订阅 / 状态缓冲 / 模拟策略" }],
    progress: { label: "进行中", tone: "in_progress", detail: "回调管理页已落地" },
  },
  {
    id: "audit",
    path: "/audit",
    navLabel: "审计日志",
    eyebrow: "Audit",
    title: "审计日志",
    description: "查看账户、模板、接管与回放等审计记录",
    visibleInNav: true,
    group: "devops",
    order: 20,
    icon: "audit",
    dataBadges: [{ label: "API", tone: "api", detail: "审计日志" }],
    progress: { label: "已接通", tone: "done", detail: "审计列表可用" },
  },
  {
    id: "system_logs",
    path: "/system/logs",
    navLabel: "系统日志",
    eyebrow: "System",
    title: "系统日志",
    description: "查看审计、状态回放与队列失败日志（已合并入审计日志 Tab）",
    visibleInNav: false,
    group: "devops",
    order: 25,
    icon: "system_logs",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "审计 / 状态缓冲 / 队列失败任务" }],
    progress: { label: "进行中", tone: "in_progress", detail: "聚合日志视图已落地" },
  },
  {
    id: "evidence_center",
    path: "/system/evidence-center",
    navLabel: "证据中心",
    eyebrow: "Audit",
    title: "证据中心",
    description: "管理审计导出、证据包和取证覆盖范围（已合并入审计日志 Tab）",
    visibleInNav: false,
    group: "devops",
    order: 28,
    icon: "evidence_center",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "审计 / 通道 / 队列 / 模拟导出任务" }],
    progress: { label: "进行中", tone: "in_progress", detail: "证据包与导出台已接入混合数据源" },
  },
  {
    id: "settings",
    path: "/settings",
    navLabel: "系统设置",
    eyebrow: "Settings",
    title: "系统设置",
    description: "管理 AI、知识库、运行时与账号级配置",
    visibleInNav: true,
    group: "settings",
    order: 20,
    icon: "settings",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "配置项与运行时接口组合" }],
    progress: { label: "进行中", tone: "in_progress", detail: "设置页持续完善" },
  },
  {
    id: "organization",
    path: "/system/organization",
    navLabel: "组织团队",
    eyebrow: "System",
    title: "组织与团队设置",
    description: "管理账号范围、组织单元、邀请域名和审批链",
    visibleInNav: false,
    group: "settings",
    order: 40,
    icon: "organization",
    dataBadges: [
      { label: "混合", tone: "hybrid", detail: "运行时 / 站点 / 成员 / Meta / 模拟治理" },
    ],
    progress: { label: "进行中", tone: "in_progress", detail: "组织治理页已可浏览" },
  },
  {
    id: "users",
    path: "/system/users",
    navLabel: "后台用户",
    eyebrow: "System",
    title: "平台用户",
    description: "管理平台用户和权限",
    visibleInNav: false,
    group: "people",
    order: 30,
    icon: "users",
    dataBadges: [{ label: "API", tone: "api", detail: "平台用户 / 新建用户 / 站点 / 标签" }],
    progress: { label: "已接通", tone: "done", detail: "平台用户管理已接真实接口" },
  },
  {
    id: "notifications",
    path: "/system/notifications",
    navLabel: "通知中心",
    eyebrow: "System",
    title: "通知中心",
    description: "管理通知渠道、规则联动和最近投递（已合并入告警中心 Tab）",
    visibleInNav: true,
    group: "devops",
    order: 35,
    icon: "notifications",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "告警快照 / 成员目录 / 模拟通道" }],
    progress: { label: "进行中", tone: "in_progress", detail: "通知中心已可浏览" },
  },
  {
    id: "identity_sync",
    path: "/system/identity-sync",
    navLabel: "身份同步",
    eyebrow: "Security",
    title: "身份同步 / 统一身份",
    description: "管理目录同步、统一身份映射和同步任务（已合并入安全中心 Tab）",
    visibleInNav: false,
    group: "settings",
    order: 55,
    icon: "identity_sync",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "统一身份通道 / 成员目录 / 模拟同步任务" }],
    progress: { label: "进行中", tone: "in_progress", detail: "统一身份同步台持续完善" },
  },
  {
    id: "security_settings",
    path: "/system/security-settings",
    navLabel: "安全中心",
    eyebrow: "Security",
    title: "登录与安全设置",
    description: "管理密码、会话、统一身份、双重验证与审计保留",
    visibleInNav: true,
    group: "settings",
    order: 50,
    icon: "security_settings",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "运行配置 / 模拟安全策略" }],
    progress: { label: "进行中", tone: "in_progress", detail: "安全设置已可浏览" },
  },
  {
    id: "member_access",
    path: "/system/member-access",
    navLabel: "成员授权",
    eyebrow: "Security",
    title: "成员授权绑定中心",
    description: "管理成员与角色、账号范围、页面范围的绑定关系（已合并入安全中心 Tab）",
    visibleInNav: false,
    group: "settings",
    order: 60,
    icon: "member_access",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "成员目录 / 角色绑定 / 访问结果" }],
    progress: { label: "进行中", tone: "in_progress", detail: "成员授权已可浏览" },
  },
  {
    id: "access_control",
    path: "/system/access-control",
    navLabel: "访问控制",
    eyebrow: "Security",
    title: "访问控制",
    description: "管理后台访问策略、会话与安全基线（已合并入安全中心 Tab）",
    visibleInNav: false,
    group: "settings",
    order: 65,
    icon: "security",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "成员目录 / 访问策略模拟" }],
    progress: { label: "进行中", tone: "in_progress", detail: "访问策略与后台会话已可浏览" },
  },
  {
    id: "alerts",
    path: "/system/alerts",
    navLabel: "告警中心",
    eyebrow: "System",
    title: "告警中心",
    description: "查看系统异常、超时和失败告警",
    visibleInNav: true,
    group: "devops",
    order: 30,
    icon: "alerts",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "指标 / 队列 / 审计 / 通道积压" }],
    progress: { label: "进行中", tone: "in_progress", detail: "告警中心已可浏览" },
  },
  {
    id: "provider_events",
    path: "/system/provider-events",
    navLabel: "通道事件",
    eyebrow: "System",
    title: "通道 / Webhook 事件",
    description: "查看状态回调积压和 Webhook 订阅运行态",
    visibleInNav: true,
    group: "devops",
    order: 40,
    icon: "provider_events",
    dataBadges: [{ label: "API", tone: "api", detail: "状态缓冲 / Webhook 订阅" }],
    progress: { label: "已接通", tone: "done", detail: "事件中心已接真实接口" },
  },
    {
    id: "agents",
    path: "/system/roles",
    navLabel: "代理商管理",
    eyebrow: "People",
    title: "代理商管理兼容入口",
    description: "兼容旧 /system/roles 路由，进入代理商管理工作台的角色视图。",
    visibleInNav: false,
    hideInMenu: true,
    group: "people",
    order: 40,
    icon: "agents",
    dataBadges: [{ label: "兼容", tone: "placeholder", detail: "旧角色中心入口会统一跳转到代理商管理工作台" }],
    progress: { label: "兼容", tone: "done", detail: "仅保留深链兼容，不再作为正式产品入口" },
  },
  {
    id: "reports",
    path: "/system/reports",
    navLabel: "报表中心",
    eyebrow: "System",
    title: "报表中心",
    description: "查看消息、模板与成本报表",
    visibleInNav: true,
    group: "analytics",
    order: 20,
    icon: "reports",
    dataBadges: [{ label: "API", tone: "api", detail: "指标 / WhatsApp 统计 / 模板分析" }],
    progress: { label: "进行中", tone: "in_progress", detail: "报表中心已接真实统计接口" },
  },
  {
    id: "imports",
    path: "/system/import-export",
    navLabel: "导入导出",
    eyebrow: "System",
    title: "导入导出中心",
    description: "管理知识库导入导出和迁移",
    visibleInNav: true,
    group: "devops",
    order: 50,
    icon: "imports",
    dataBadges: [{ label: "API", tone: "api", detail: "知识库导入 / 导出" }],
    progress: { label: "进行中", tone: "in_progress", detail: "导入导出中心已接真实接口" },
  },
  {
    id: "risk",
    path: "/system/risk",
    navLabel: "风控名单",
    eyebrow: "System",
    title: "黑白名单与风控",
    description: "管理黑名单、白名单和风险档案（已合并入安全中心 Tab）",
    visibleInNav: false,
    group: "settings",
    order: 70,
    icon: "risk",
    dataBadges: [{ label: "模拟", tone: "mock", detail: "风控名单与案例由前端模拟支持" }],
    progress: { label: "进行中", tone: "in_progress", detail: "风控中心已可浏览" },
  },
  {
    id: "operations",
    path: "/system/operations",
    navLabel: "运营看板",
    eyebrow: "System",
    title: "操作中心",
    description: "处理队列、通道积压和批量任务",
    visibleInNav: true,
    group: "analytics",
    order: 30,
    icon: "operations",
    dataBadges: [{ label: "混合", tone: "hybrid", detail: "队列 / 任务 / 通道积压 / 模拟批量任务" }],
    progress: { label: "进行中", tone: "in_progress", detail: "操作中心已可浏览" },
  },
  {
    id: "profile",
    path: "/profile",
    navLabel: "个人中心",
    eyebrow: "Profile",
    title: "个人中心",
    description: "查看个人信息和修改密码",
    visibleInNav: false,
    group: "settings",
    order: 100,
    icon: "settings",
    dataBadges: [],
    progress: { label: "已接通", tone: "done", detail: "通用个人中心页面" },
  },
  {
    id: "sites",
    path: "/system/sites",
    navLabel: "站点",
    eyebrow: "System",
    title: "站点管理",
    description: "管理 H5 站点的完整生命周期，包括创建、编辑、删除、部署",
    visibleInNav: true,
    group: "settings",
    order: 32,
    icon: "sites",
    dataBadges: [{ label: "API", tone: "api", detail: "平台站点 / 新建站点" }],
    progress: { label: "已接通", tone: "done", detail: "站点管理已接真实接口" },
  },
  {
    id: "entry_links",
    path: "/system/entry-links",
    navLabel: "入口链接",
    eyebrow: "System",
    title: "入口链接运营管理",
    description: "客服 / AI / 站点总入口链接、二维码、广告链接的列表、创建、复制、撤销、轮换与 stats",
    visibleInNav: true,
    group: "settings",
    order: 33,
    icon: "sites",
    dataBadges: [{ label: "API", tone: "api", detail: "EntryLink CRUD / 撤销 / 轮换" }],
    progress: { label: "已接通", tone: "done", detail: "EntryLink 运营页接真实接口" },
  },
  {
    id: "debug_panel",
    path: "/debug",
    navLabel: "链路调试",
    eyebrow: "DevOps",
    title: "链路调试面板",
    description: "全链路连通性诊断 - 检测数据库、缓存、队列、Meta 账户对接状态",
    visibleInNav: true,
    group: "devops",
    order: 5,
    icon: "debug",
    dataBadges: [{ label: "诊断", tone: "api", detail: "健康检测 / 链路状态 / 账户诊断" }],
    progress: { label: "已接通", tone: "done", detail: "全链路诊断面板已上线" },
  },
  {
    id: "whatsapp_api_test",
    path: "/whatsapp-api-test",
    navLabel: "WhatsApp API 测试",
    eyebrow: "DevOps",
    title: "WhatsApp API 参数调试",
    description: "Token 验证、消息发送、号码查询、Webhook 配置 — Meta Cloud API 测试工具",
    visibleInNav: true,
    group: "devops",
    order: 6,
    icon: "api_test",
    dataBadges: [{ label: "API", tone: "api", detail: "Token 验证 / 消息发送 / 号码查询 / Webhook" }],
    progress: { label: "已接通", tone: "done", detail: "API 调试面板已上线" },
  },
  {
    id: "agents",
    path: "/system/agents",
    navLabel: "代理商管理",
    eyebrow: "People",
    title: "代理商管理",
    description: "统一管理代理商、权限池、角色、成员与账单工作台。",
    visibleInNav: true,
    group: "people",
    order: 33,
    icon: "agents",
    dataBadges: [{ label: "API", tone: "api", detail: "代理商、角色、成员、账单" }],
    progress: { label: "进行中", tone: "in_progress", detail: "单页工作台已上线，继续补全交互与链路" },
  },
  // IV-FE: New system routes
  {
    id: "backups",
    path: "/system/backups",
    navLabel: "数据库备份",
    eyebrow: "System",
    title: "数据库备份",
    description: "管理和恢复数据库备份",
    visibleInNav: true,
    group: "devops",
    order: 45,
    icon: "monitoring",
    dataBadges: [{ label: "API", tone: "api", detail: "备份 / 恢复 / 自动备份" }],
    progress: { label: "新功能", tone: "in_progress", detail: "数据库备份恢复" },
  },
  {
    id: "knowledge",
    path: "/system/knowledge",
    navLabel: "知识库",
    eyebrow: "System",
    title: "知识库管理",
    description: "管理知识分类和文章",
    visibleInNav: true,
    group: "settings",
    order: 35,
    icon: "templates",
    dataBadges: [{ label: "API", tone: "api", detail: "分类 / 文章 / 搜索" }],
    progress: { label: "新功能", tone: "in_progress", detail: "知识库管理" },
  },
  {
    id: "api_stats",
    path: "/system/api-stats",
    navLabel: "API 统计",
    eyebrow: "System",
    title: "API 调用统计",
    description: "查看 API 调用统计数据",
    visibleInNav: true,
    group: "analytics",
    order: 35,
    icon: "analytics",
    dataBadges: [{ label: "API", tone: "api", detail: "汇总 / 按代理商 / 按端点" }],
    progress: { label: "新功能", tone: "in_progress", detail: "API 调用统计" },
  },
  {
    id: "rate_limits",
    path: "/system/rate-limits",
    navLabel: "频率限制",
    eyebrow: "System",
    title: "API 频率限制",
    description: "配置 API 调用频率限制和 IP 封禁规则",
    visibleInNav: true,
    group: "devops",
    order: 46,
    icon: "security",
    dataBadges: [{ label: "API", tone: "api", detail: "规则 / 封禁 IP" }],
    progress: { label: "新功能", tone: "in_progress", detail: "频率限制管理" },
  },
  {
    id: "ai_chat_config",
    path: "/system/ai-chat-config",
    navLabel: "AI 聊天配置",
    eyebrow: "System",
    title: "AI 聊天配置",
    description: "配置 AI 智能聊天参数、工具调用和测试聊天",
    visibleInNav: true,
    group: "settings",
    order: 36,
    icon: "ai_chat",
    dataBadges: [{ label: "新功能", tone: "mock", detail: "AI 聊天配置" }],
    progress: { label: "新功能", tone: "in_progress", detail: "AI 聊天配置" },
  },
  // Finance routes
  {
    id: "finance_settings",
    path: "/system/finance-settings",
    navLabel: "财务设置",
    eyebrow: "Finance",
    title: "财务设置",
    description: "管理支付渠道、汇率和 AI 计费配置",
    visibleInNav: true,
    group: "finance",
    order: 10,
    icon: "settings",
    dataBadges: [{ label: "API", tone: "api", detail: "支付渠道 / 汇率 / AI 计费" }],
    progress: { label: "已接通", tone: "done", detail: "财务设置已接正式页面" },
  },
  {
    id: "finance",
    path: "/system/finance",
    navLabel: "财务管理",
    eyebrow: "Finance",
    title: "财务管理",
    description: "查看充值、提现、钱包流水和财务报表",
    visibleInNav: true,
    group: "finance",
    order: 20,
    icon: "ecommerce",
    dataBadges: [{ label: "API", tone: "api", detail: "充值 / 提现 / 钱包流水 / 告警" }],
    progress: { label: "已接通", tone: "done", detail: "财务管理已接真实数据链路" },
  },
  // Agent pages (not in standard nav - routed via agent prefix)
  {
    id: "agent_usage",
    path: "/agent/usage",
    navLabel: "用量查看",
    eyebrow: "Agent",
    title: "用量查看",
    description: "AI 和翻译服务使用情况",
    visibleInNav: false,
    group: "analytics",
    order: 5,
    icon: "analytics",
    dataBadges: [{ label: "新功能", tone: "mock", detail: "用量查看" }],
    progress: { label: "新功能", tone: "in_progress", detail: "用量查看" },
  },
  {
    id: "agent_finance_settings",
    path: "/agent/finance-settings",
    navLabel: "财务设置",
    eyebrow: "Agent",
    title: "财务设置",
    description: "支付渠道和提现规则",
    visibleInNav: false,
    group: "settings",
    order: 41,
    icon: "settings",
    dataBadges: [{ label: "新功能", tone: "mock", detail: "财务设置" }],
    progress: { label: "新功能", tone: "in_progress", detail: "财务设置" },
  },
  {
    id: "agent_finance",
    path: "/agent/finance",
    navLabel: "财务管理",
    eyebrow: "Agent",
    title: "财务管理",
    description: "站点充值提现管理",
    visibleInNav: false,
    group: "analytics",
    order: 6,
    icon: "reports",
    dataBadges: [{ label: "新功能", tone: "mock", detail: "财务管理" }],
    progress: { label: "新功能", tone: "in_progress", detail: "财务管理" },
  },
];

const ROUTES_BY_ID = new Map<AppPageId, ConsoleRouteDefinition>();
for (const route of CONSOLE_ROUTES) {
  const existing = ROUTES_BY_ID.get(route.id);
  if (!existing || (existing.hideInMenu && !route.hideInMenu)) {
    ROUTES_BY_ID.set(route.id, route);
  }
}

export const primaryConsoleRoutes = CONSOLE_ROUTES.filter(
  (route) => route.visibleInNav && !route.hideInMenu
);

function buildGroup(group: ConsoleRouteGroup): ConsoleRouteDefinition[] {
  return CONSOLE_ROUTES
    .filter((route) => route.group === group && route.visibleInNav && !route.hideInMenu)
    .sort((left, right) => left.order - right.order);
}

export const groupedConsoleRoutes = {
  workspace: buildGroup("workspace"),
  content: buildGroup("content"),
  people: buildGroup("people"),
  analytics: buildGroup("analytics"),
  finance: buildGroup("finance"),
  settings: buildGroup("settings"),
  devops: buildGroup("devops"),
} satisfies Record<ConsoleRouteGroup, ConsoleRouteDefinition[]>;

function normalizePathname(pathname: string): string {
  if (!pathname.startsWith("/")) {
    return "/";
  }
  if (pathname.length > 1 && pathname.endsWith("/")) {
    return pathname.slice(0, -1);
  }
  return pathname;
}

export function getConsoleRouteById(pageId: AppPageId): ConsoleRouteDefinition | undefined {
  return ROUTES_BY_ID.get(pageId);
}

export function getConsolePath(pageId: AppPageId): string {
  return getConsoleRouteById(pageId)?.path ?? "/";
}

export function resolveConsoleRoute(pathname: string): ConsoleRouteDefinition {
  const normalizedPathname = normalizePathname(pathname);
  const directMatch = CONSOLE_ROUTES.find((route) => route.path === normalizedPathname);
  if (directMatch) {
    return directMatch;
  }

  const prefixMatch = [...CONSOLE_ROUTES]
    .sort((left, right) => right.path.length - left.path.length)
    .find((route) => route.path !== "/" && normalizedPathname.startsWith(`${route.path}/`));

  return prefixMatch ?? CONSOLE_ROUTES[0];
}


